name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
 # Send HTTP POST request if the build fails
    - name: Notify on failure
      if: failure()
      run: |
        curl -X POST https://teams-sandbox.alanj.live/api/build-failure \
        -H 'Content-Type: application/json' \
        -d '{
          "status": "failure",
          "message": "Docker build failed",
          "repository": "${{ github.repository }}",
          "commit": "${{ github.sha }}",
          "author": "${{ github.actor }}"
        }'
